
import Nav from "../components/nav/Nav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
                <div className="w-[100vw] h-[100vh]">
            <Nav/>
            <div className="pt-26 p-16">
                <div>

                </div>
                {children}
            </div>
        </div>

      </body>
    </html>
  );
}

